### ISSUE TITLE
Containerization of a React app

### ISSUE THREAD

**Issue by rpmolina** [nanlabs/devops-reference#70]

**Comment by Siddharth9890** [comment]
@ulises-jeremias can i try this

**Comment by ulises-jeremias** [comment]
@Siddharth9890 sure!

**Comment by Siddharth9890** [comment]
hey @ulises-jeremias i have a doubt i have made a docker compose file just for testing is this fine?

```

version: '3'


volumes:
  postgres-data:
    name: my-app-postgres-data
  
services:
  frontend:
    build:
      context: ./frontend  
    environment:
      - REACT_APP_PORT=3000  
    ports:
      - ${REACT_APP_PORT}:3000 
   

  backend:
    build:
      context: ./backend  
    environment:
      - NODE_API_PORT=8080
    ports:
      - ${NODE_API_PORT}:8000 
    depends_on:
      - database  

  database:
    image: postgres:13  # Use a specific version of PostgreSQL
    environment:
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    volumes:
      - postgres-data:/var/lib/postgresql/data 

```
